# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 80775d6615ac60ab066cb24626d5d08796177e46aa6ed2df02ac2ac02e73b23a450343c6735a89bb2bd92db9ff2277b153ff987505449709bbd9a6a25bd6e5f8

test:
  secret_key_base: e35465ea44974ef7522fc11d1db245b0b9d8c6d0ebab1bcaba97190b6ec362345e2cb23e01cb708e8442fcb248794f1d22208314a32f0a1b4cc821e1e20833f7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
